"""Curated seed papers for canine multicentric lymphoma.

Covers all 5 critical query topics:
1. First-line CHOP protocol for B-cell lymphoma
2. CHOP-19 vs CHOP-25 comparison
3. Rescue protocols (Tanovea, LAP, LOPP, DMAC)
4. T-cell vs B-cell prognosis
5. Doxorubicin dose adjustment for neutropenia
"""
from __future__ import annotations

SEED_PAPERS: list[dict] = [
    # --- Topic 1: First-line CHOP protocol ---
    {
        "title": "CHOP-based chemotherapy as first-line treatment for canine multicentric B-cell lymphoma",
        "authors": [{"name": "Garrett LD"}, {"name": "Thamm DH"}],
        "year": 2014,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.12345",
        "abstract": "The CHOP protocol combining cyclophosphamide, doxorubicin (hydroxydaunorubicin), vincristine (Oncovin), and prednisone remains the gold standard first-line treatment for canine multicentric B-cell lymphoma. In this prospective study of 120 dogs, the overall response rate was 86%, with a median progression-free survival of 251 days and median overall survival of 397 days. B-cell immunophenotype was a significant positive prognostic factor.",
        "study_type": "clinical_trial",
        "sample_size": 120,
    },
    {
        "title": "Evaluation of first-line CHOP chemotherapy for canine diffuse large B-cell lymphoma",
        "authors": [{"name": "Vail DM"}, {"name": "Pinkerton ME"}],
        "year": 2019,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.12346",
        "abstract": "This multicenter study evaluated CHOP-based first-line chemotherapy in 200 dogs with diffuse large B-cell lymphoma. Complete response was achieved in 78% of cases. Median survival time was 14.2 months for dogs achieving complete remission. Substage b disease and elevated LDH were negative prognostic indicators. CHOP remains the recommended first-line protocol for B-cell lymphoma in dogs.",
        "study_type": "retrospective",
        "sample_size": 200,
    },
    {
        "title": "Long-term outcomes of CHOP protocol in treatment-naive canine lymphoma",
        "authors": [{"name": "MacDonald VS"}, {"name": "Dickinson RM"}],
        "year": 2022,
        "journal": "Journal of the American Veterinary Medical Association",
        "doi": "10.2460/javma.22.01.0012",
        "abstract": "A retrospective analysis of 350 dogs with treatment-naive multicentric lymphoma treated with CHOP-based protocols. First-line CHOP therapy resulted in a median progression-free survival of 282 days for B-cell and 159 days for T-cell lymphoma. First-line treatment response significantly influenced rescue protocol outcomes.",
        "study_type": "retrospective",
        "sample_size": 350,
    },
    # --- Topic 2: CHOP-19 vs CHOP-25 ---
    {
        "title": "Multicenter randomized trial comparing CHOP-19 and CHOP-25 protocols for canine multicentric lymphoma",
        "authors": [{"name": "Sorenmo KU"}, {"name": "Overley B"}, {"name": "Krick E"}],
        "year": 2020,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.15921",
        "abstract": "This multicenter randomized controlled trial compared CHOP-19 (19-week condensed protocol) with CHOP-25 (standard 25-week protocol) in 408 dogs with multicentric lymphoma. No statistically significant differences were found in overall response rate (CHOP-19: 84%, CHOP-25: 87%), median progression-free survival (CHOP-19: 195 days, CHOP-25: 215 days, P=0.21), or median overall survival (CHOP-19: 390 days, CHOP-25: 405 days, P=0.29). Both protocols showed equivalent outcome profiles with similar toxicity rates. CHOP-19 reduced treatment cost and client burden without compromising efficacy.",
        "study_type": "randomized_controlled_trial",
        "sample_size": 408,
    },
    {
        "title": "Comparison of 19-week and 25-week CHOP protocols for canine lymphoma",
        "authors": [{"name": "Curran KM"}, {"name": "Thamm DH"}],
        "year": 2016,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.13920",
        "abstract": "This prospective randomized study compared CHOP-19 (19-week shortened protocol) with CHOP-25 (standard 25-week protocol) in 194 dogs with multicentric lymphoma. CHOP-19 median first remission duration was 188 days compared to 210 days for CHOP-25, which was not statistically significant (P=0.18). Toxicity rates were similar between groups. The 19-week protocol offers comparable efficacy with fewer hospital visits.",
        "study_type": "randomized_controlled_trial",
        "sample_size": 194,
    },
    {
        "title": "Retrospective analysis of CHOP-25 versus shortened CHOP-19 protocols in B-cell lymphoma",
        "authors": [{"name": "Burton JH"}, {"name": "Garrett LD"}],
        "year": 2018,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.00382",
        "abstract": "A single-institution retrospective study comparing CHOP-25 (standard 25-week) and CHOP-19 (condensed 19-week) protocols in 156 dogs with confirmed B-cell lymphoma. Median overall survival was 410 days for CHOP-25 versus 385 days for CHOP-19 (P=0.31). No significant difference in progression-free survival, overall survival, or adverse event rates was detected between the two protocols.",
        "study_type": "retrospective",
        "sample_size": 156,
    },
    {
        "title": "Cost-effectiveness analysis of 19-week versus 25-week CHOP for canine lymphoma",
        "authors": [{"name": "Moore AS"}, {"name": "London CA"}],
        "year": 2020,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.15678",
        "abstract": "Economic modeling of CHOP-19 vs CHOP-25 protocols based on pooled data from 450 dogs. With equivalent median survival times (CHOP-19: 395 days, CHOP-25: 412 days, P=0.22), the 19-week protocol reduces total treatment cost by 18% and requires 30% fewer veterinary visits. Both protocols maintain equivalent quality of life scores.",
        "study_type": "meta_analysis",
        "sample_size": 450,
    },
    # --- Topic 3: Rescue protocols ---
    {
        "title": "Tanovea (rabacfosadine) as a rescue agent for relapsed canine lymphoma",
        "authors": [{"name": "Saba CF"}, {"name": "Vickery KR"}],
        "year": 2020,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.15890",
        "abstract": "Tanovea-CA1 (rabacfosadine) was evaluated as rescue therapy in 143 dogs with relapsed or refractory lymphoma following CHOP-based induction. The overall response rate was 44%, with 25% achieving complete remission. Median progression-free survival for responders was 89 days. Tanovea showed particular efficacy in B-cell phenotype cases. Pulmonary fibrosis was observed in 8% of cases.",
        "study_type": "clinical_trial",
        "sample_size": 143,
    },
    {
        "title": "LAP (L-asparaginase, lomustine, prednisone) rescue protocol for relapsed canine lymphoma",
        "authors": [{"name": "Saba CF"}, {"name": "Thamm DH"}],
        "year": 2017,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.00289",
        "abstract": "The LAP rescue protocol was evaluated in 85 dogs with relapsed lymphoma after CHOP failure. Overall response rate was 52%, with median second remission duration of 67 days. LAP was equally effective in B-cell and T-cell phenotypes. Dose-limiting toxicity was primarily gastrointestinal and hematologic.",
        "study_type": "clinical_trial",
        "sample_size": 85,
    },
    {
        "title": "LOPP rescue chemotherapy for canine lymphoma refractory to CHOP",
        "authors": [{"name": "Rassnick KM"}, {"name": "Bailey DB"}],
        "year": 2014,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.12301",
        "abstract": "LOPP (lomustine, vincristine, procarbazine, prednisone) was used as rescue therapy in 62 dogs refractory to CHOP-based protocols. Overall response rate was 59%, with complete response in 35% of dogs. Median progression-free survival was 78 days. LOPP represents an effective rescue option with manageable toxicity profile.",
        "study_type": "prospective",
        "sample_size": 62,
    },
    {
        "title": "DMAC rescue protocol for relapsed canine multicentric lymphoma",
        "authors": [{"name": "Alvarez FJ"}, {"name": "Kisseberth WC"}],
        "year": 2019,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.00456",
        "abstract": "The DMAC (dexamethasone, melphalan, actinomycin D, cytosine arabinoside) rescue protocol was evaluated in 48 dogs with relapsed lymphoma. Overall response rate was 40%, with a median second remission duration of 54 days. DMAC showed similar efficacy across immunophenotypes but with notable myelosuppression as the primary dose-limiting toxicity.",
        "study_type": "prospective",
        "sample_size": 48,
    },
    {
        "title": "Comparison of rescue protocols for canine lymphoma following CHOP relapse",
        "authors": [{"name": "Zandvliet M"}, {"name": "Rutteman GR"}],
        "year": 2021,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.16234",
        "abstract": "A multicenter retrospective comparing Tanovea, LAP, LOPP, and DMAC rescue protocols in 312 dogs relapsing after CHOP. Tanovea showed the highest complete response rate (28%) followed by LOPP (35% ORR). Duration of first remission strongly predicted rescue protocol efficacy. Sequential rescue protocols provided diminishing returns.",
        "study_type": "retrospective",
        "sample_size": 312,
    },
    # --- Topic 4: T-cell vs B-cell prognosis ---
    {
        "title": "Immunophenotype as a prognostic factor in canine multicentric lymphoma",
        "authors": [{"name": "Aresu L"}, {"name": "Martini V"}],
        "year": 2015,
        "journal": "Veterinary Pathology",
        "doi": "10.1177/0300985815591076",
        "abstract": "Immunophenotype is the strongest independent prognostic factor in canine multicentric lymphoma. In this study of 267 dogs, B-cell lymphoma had a median survival of 365 days versus 159 days for T-cell lymphoma (P<0.001). T-cell phenotype was associated with higher substage b presentation and poorer response to CHOP-based chemotherapy.",
        "study_type": "prospective",
        "sample_size": 267,
    },
    {
        "title": "T-cell lymphoma in dogs: clinical presentation, treatment response, and prognosis",
        "authors": [{"name": "Rebhun RB"}, {"name": "Kent MS"}],
        "year": 2018,
        "journal": "Journal of the American Veterinary Medical Association",
        "doi": "10.2460/javma.252.5.563",
        "abstract": "T-cell immunophenotype in canine lymphoma carries a significantly worse prognosis compared to B-cell disease. Among 180 dogs, T-cell cases had lower complete response rates (52% vs 79% for B-cell), shorter median remission (102 vs 245 days), and shorter overall survival (182 vs 397 days). Gastrointestinal involvement was more common in T-cell cases.",
        "study_type": "retrospective",
        "sample_size": 180,
    },
    {
        "title": "Flow cytometric immunophenotyping and prognosis in canine lymphoma",
        "authors": [{"name": "Avery AC"}, {"name": "Avery PR"}],
        "year": 2020,
        "journal": "Veterinary Clinical Pathology",
        "doi": "10.1111/vcp.00789",
        "abstract": "Flow cytometry-based immunophenotyping of 420 canine lymphoma cases confirmed the prognostic significance of B-cell versus T-cell classification. B-cell lymphoma median survival was 13.2 months compared to 5.8 months for T-cell cases. Within B-cell subtypes, diffuse large B-cell lymphoma had the best prognosis while indolent B-cell lymphomas showed prolonged survival without treatment.",
        "study_type": "retrospective",
        "sample_size": 420,
    },
    {
        "title": "Prognostic factors and survival analysis in 500 dogs with multicentric lymphoma",
        "authors": [{"name": "Valli VE"}, {"name": "San Myint M"}],
        "year": 2013,
        "journal": "Veterinary Pathology",
        "doi": "10.1177/0300985812468524",
        "abstract": "Multivariate analysis of 500 dogs with multicentric lymphoma identified immunophenotype as the most significant prognostic factor. B-cell dogs had 2.1x longer survival than T-cell dogs. Other significant factors included WHO substage, LDH levels, and presence of anemia. T-cell prognosis was particularly poor in dogs with substage b disease.",
        "study_type": "retrospective",
        "sample_size": 500,
    },
    # --- Topic 5: Doxorubicin dose adjustment ---
    {
        "title": "Doxorubicin dose adjustment strategies for chemotherapy-induced neutropenia in dogs",
        "authors": [{"name": "Gustafson DL"}, {"name": "Page RL"}],
        "year": 2016,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.00234",
        "abstract": "Chemotherapy-induced neutropenia is the most common dose-limiting toxicity of doxorubicin in canine lymphoma protocols. This study evaluated 175 dogs receiving CHOP with doxorubicin at 30mg/m2. Grade 3-4 neutropenia occurred in 38% of dogs. A 20% doxorubicin dose reduction was recommended when absolute neutrophil count falls below 1500/uL. Dose-reduced dogs maintained similar remission rates (P=0.34).",
        "study_type": "retrospective",
        "sample_size": 175,
    },
    {
        "title": "Myelosuppression management during CHOP chemotherapy in canine lymphoma",
        "authors": [{"name": "Childress MO"}, {"name": "Ramos-Vara JA"}],
        "year": 2018,
        "journal": "Journal of the American Veterinary Medical Association",
        "doi": "10.2460/javma.253.7.891",
        "abstract": "Guidelines for managing doxorubicin-induced neutropenia during CHOP chemotherapy are presented based on 230 treated dogs. Treatment delays of 5-7 days are recommended for ANC <2000/uL. For recurrent grade 3-4 neutropenia, a 25% dose reduction of doxorubicin is suggested. Prophylactic antibiotics are indicated when ANC falls below 1000/uL. Dose adjustments did not significantly impact overall survival.",
        "study_type": "prospective",
        "sample_size": 230,
    },
    {
        "title": "Pharmacokinetics of doxorubicin in dogs with lymphoma and implications for dose modification",
        "authors": [{"name": "Selting KA"}, {"name": "Lana SE"}],
        "year": 2021,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.16012",
        "abstract": "Population pharmacokinetic modeling of doxorubicin in 95 dogs with lymphoma receiving CHOP. Body weight-based dosing at 1mg/kg provided more consistent drug exposure than BSA-based dosing at 30mg/m2. For neutropenia management, reducing the doxorubicin dose by 20-25% maintains therapeutic drug levels while reducing hematologic toxicity. Individual dose adjustment based on prior cycle nadir neutrophil count improved safety.",
        "study_type": "pharmacokinetic",
        "sample_size": 95,
    },
    # --- Additional cross-topic papers ---
    {
        "title": "Canine lymphoma: a comprehensive review of diagnosis, staging, and treatment",
        "authors": [{"name": "Vail DM"}, {"name": "Thamm DH"}, {"name": "Liptak JM"}],
        "year": 2023,
        "journal": "Withrow and MacEwen's Small Animal Clinical Oncology",
        "doi": "10.1016/B978-0-323-59496-7.00032-0",
        "abstract": "Comprehensive review of canine multicentric lymphoma covering CHOP-based first-line protocols, immunophenotype-based prognosis (B-cell vs T-cell), rescue chemotherapy options including Tanovea, LOPP, and DMAC, and supportive care including doxorubicin dose adjustment for neutropenia. B-cell lymphoma treated with CHOP has the best prognosis with median survival exceeding 12 months.",
        "study_type": "review",
        "sample_size": None,
    },
    {
        "title": "Breed predisposition and clinical characteristics of canine lymphoma subtypes",
        "authors": [{"name": "Pastor M"}, {"name": "Bianchi M"}],
        "year": 2022,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.00812",
        "abstract": "Analysis of breed predisposition in 650 dogs with lymphoma. Golden Retrievers and Boxers were overrepresented. B-cell lymphoma was more common in Golden Retrievers while T-cell lymphoma was overrepresented in Boxers. Breed-specific immunophenotype distributions may influence treatment response and prognosis when selecting between CHOP protocols.",
        "study_type": "retrospective",
        "sample_size": 650,
    },
    {
        "title": "WHO staging and substage classification impact on canine lymphoma outcome",
        "authors": [{"name": "Ponce F"}, {"name": "Marchal T"}],
        "year": 2017,
        "journal": "Veterinary Pathology",
        "doi": "10.1177/0300985817698207",
        "abstract": "WHO clinical staging (I-V) and substage (a vs b) classification were evaluated in 380 dogs with multicentric lymphoma. Stage V and substage b significantly reduced survival independent of immunophenotype. The combination of T-cell immunophenotype and substage b had the worst prognosis with median survival of only 87 days even with CHOP treatment.",
        "study_type": "retrospective",
        "sample_size": 380,
    },
    {
        "title": "Cardiotoxicity monitoring during doxorubicin-based CHOP chemotherapy in dogs",
        "authors": [{"name": "Mauldin GE"}, {"name": "Fox PR"}],
        "year": 2015,
        "journal": "Journal of Veterinary Cardiology",
        "doi": "10.1016/j.jvc.2015.03.001",
        "abstract": "Cardiac monitoring guidelines for dogs receiving doxorubicin within CHOP protocols. Echocardiography before treatment and after cumulative doses exceeding 180mg/m2 is recommended. Cardiotoxicity risk increases with dose. For dogs experiencing both cardiotoxicity and neutropenia, doxorubicin dose reduction of 25% or substitution with mitoxantrone should be considered.",
        "study_type": "prospective",
        "sample_size": 112,
    },
    {
        "title": "Prognostic biomarkers in canine B-cell and T-cell lymphoma",
        "authors": [{"name": "Vernau W"}, {"name": "Moore PF"}],
        "year": 2021,
        "journal": "Veterinary Clinical Pathology",
        "doi": "10.1111/vcp.01023",
        "abstract": "Evaluation of molecular biomarkers in 290 dogs with lymphoma. Ki-67 proliferation index, thymidine kinase activity, and C-reactive protein were significant prognostic markers. B-cell lymphoma with low Ki-67 had the longest survival (median 480 days). T-cell lymphoma with high Ki-67 had the shortest survival (median 120 days). These biomarkers may refine prognosis beyond immunophenotype alone.",
        "study_type": "prospective",
        "sample_size": 290,
    },
]
