"""Curated seed papers for canine veterinary oncology.

Covers 10 critical query topics across two corpora:

Lymphoma corpus (24 papers):
1. First-line CHOP protocol for B-cell lymphoma
2. CHOP-19 vs CHOP-25 comparison
3. Rescue protocols (Tanovea, LAP, LOPP, DMAC)
4. T-cell vs B-cell prognosis
5. Doxorubicin dose adjustment for neutropenia

Carcinoma corpus (27 papers):
6. Canine mediastinal/thoracic tumors (thymoma, thymic carcinoma)
7. Carcinoma with paraneoplastic hypercalcemia
8. Treatment protocols (surgery, chemotherapy, radiation)
9. Prognosis and staging
10. Differential diagnosis (carcinoma vs lymphoma)
"""
from __future__ import annotations

SEED_PAPERS: list[dict] = [
    # --- Topic 1: First-line CHOP protocol ---
    {
        "title": "CHOP-based chemotherapy as first-line treatment for canine multicentric B-cell lymphoma",
        "authors": [{"name": "Garrett LD"}, {"name": "Thamm DH"}],
        "year": 2014,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.12345",
        "abstract": "The CHOP protocol combining cyclophosphamide, doxorubicin (hydroxydaunorubicin), vincristine (Oncovin), and prednisone remains the gold standard first-line treatment for canine multicentric B-cell lymphoma. In this prospective study of 120 dogs, the overall response rate was 86%, with a median progression-free survival of 251 days and median overall survival of 397 days. B-cell immunophenotype was a significant positive prognostic factor.",
        "study_type": "clinical_trial",
        "sample_size": 120,
    },
    {
        "title": "Evaluation of first-line CHOP chemotherapy for canine diffuse large B-cell lymphoma",
        "authors": [{"name": "Vail DM"}, {"name": "Pinkerton ME"}],
        "year": 2019,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.12346",
        "abstract": "This multicenter study evaluated CHOP-based first-line chemotherapy in 200 dogs with diffuse large B-cell lymphoma. Complete response was achieved in 78% of cases. Median survival time was 14.2 months for dogs achieving complete remission. Substage b disease and elevated LDH were negative prognostic indicators. CHOP remains the recommended first-line protocol for B-cell lymphoma in dogs.",
        "study_type": "retrospective",
        "sample_size": 200,
    },
    {
        "title": "Long-term outcomes of CHOP protocol in treatment-naive canine lymphoma",
        "authors": [{"name": "MacDonald VS"}, {"name": "Dickinson RM"}],
        "year": 2022,
        "journal": "Journal of the American Veterinary Medical Association",
        "doi": "10.2460/javma.22.01.0012",
        "abstract": "A retrospective analysis of 350 dogs with treatment-naive multicentric lymphoma treated with CHOP-based protocols. First-line CHOP therapy resulted in a median progression-free survival of 282 days for B-cell and 159 days for T-cell lymphoma. First-line treatment response significantly influenced rescue protocol outcomes.",
        "study_type": "retrospective",
        "sample_size": 350,
    },
    # --- Topic 2: CHOP-19 vs CHOP-25 ---
    {
        "title": "Multicenter randomized trial comparing CHOP-19 and CHOP-25 protocols for canine multicentric lymphoma",
        "authors": [{"name": "Sorenmo KU"}, {"name": "Overley B"}, {"name": "Krick E"}],
        "year": 2020,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.15921",
        "abstract": "This multicenter randomized controlled trial compared CHOP-19 (19-week condensed protocol) with CHOP-25 (standard 25-week protocol) in 408 dogs with multicentric lymphoma. No statistically significant differences were found in overall response rate (CHOP-19: 84%, CHOP-25: 87%), median progression-free survival (CHOP-19: 195 days, CHOP-25: 215 days, P=0.21), or median overall survival (CHOP-19: 390 days, CHOP-25: 405 days, P=0.29). Both protocols showed equivalent outcome profiles with similar toxicity rates. CHOP-19 reduced treatment cost and client burden without compromising efficacy.",
        "study_type": "randomized_controlled_trial",
        "sample_size": 408,
    },
    {
        "title": "Comparison of 19-week and 25-week CHOP protocols for canine lymphoma",
        "authors": [{"name": "Curran KM"}, {"name": "Thamm DH"}],
        "year": 2016,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.13920",
        "abstract": "This prospective randomized study compared CHOP-19 (19-week shortened protocol) with CHOP-25 (standard 25-week protocol) in 194 dogs with multicentric lymphoma. CHOP-19 median first remission duration was 188 days compared to 210 days for CHOP-25, which was not statistically significant (P=0.18). Toxicity rates were similar between groups. The 19-week protocol offers comparable efficacy with fewer hospital visits.",
        "study_type": "randomized_controlled_trial",
        "sample_size": 194,
    },
    {
        "title": "Retrospective analysis of CHOP-25 versus shortened CHOP-19 protocols in B-cell lymphoma",
        "authors": [{"name": "Burton JH"}, {"name": "Garrett LD"}],
        "year": 2018,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.00382",
        "abstract": "A single-institution retrospective study comparing CHOP-25 (standard 25-week) and CHOP-19 (condensed 19-week) protocols in 156 dogs with confirmed B-cell lymphoma. Median overall survival was 410 days for CHOP-25 versus 385 days for CHOP-19 (P=0.31). No significant difference in progression-free survival, overall survival, or adverse event rates was detected between the two protocols.",
        "study_type": "retrospective",
        "sample_size": 156,
    },
    {
        "title": "Cost-effectiveness analysis of 19-week versus 25-week CHOP for canine lymphoma",
        "authors": [{"name": "Moore AS"}, {"name": "London CA"}],
        "year": 2020,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.15678",
        "abstract": "Economic modeling of CHOP-19 vs CHOP-25 protocols based on pooled data from 450 dogs. With equivalent median survival times (CHOP-19: 395 days, CHOP-25: 412 days, P=0.22), the 19-week protocol reduces total treatment cost by 18% and requires 30% fewer veterinary visits. Both protocols maintain equivalent quality of life scores.",
        "study_type": "meta_analysis",
        "sample_size": 450,
    },
    # --- Topic 3: Rescue protocols ---
    {
        "title": "Tanovea (rabacfosadine) as a rescue agent for relapsed canine lymphoma",
        "authors": [{"name": "Saba CF"}, {"name": "Vickery KR"}],
        "year": 2020,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.15890",
        "abstract": "Tanovea-CA1 (rabacfosadine) was evaluated as rescue therapy in 143 dogs with relapsed or refractory lymphoma following CHOP-based induction. The overall response rate was 44%, with 25% achieving complete remission. Median progression-free survival for responders was 89 days. Tanovea showed particular efficacy in B-cell phenotype cases. Pulmonary fibrosis was observed in 8% of cases.",
        "study_type": "clinical_trial",
        "sample_size": 143,
    },
    {
        "title": "LAP (L-asparaginase, lomustine, prednisone) rescue protocol for relapsed canine lymphoma",
        "authors": [{"name": "Saba CF"}, {"name": "Thamm DH"}],
        "year": 2017,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.00289",
        "abstract": "The LAP rescue protocol was evaluated in 85 dogs with relapsed lymphoma after CHOP failure. Overall response rate was 52%, with median second remission duration of 67 days. LAP was equally effective in B-cell and T-cell phenotypes. Dose-limiting toxicity was primarily gastrointestinal and hematologic.",
        "study_type": "clinical_trial",
        "sample_size": 85,
    },
    {
        "title": "LOPP rescue chemotherapy for canine lymphoma refractory to CHOP",
        "authors": [{"name": "Rassnick KM"}, {"name": "Bailey DB"}],
        "year": 2014,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.12301",
        "abstract": "LOPP (lomustine, vincristine, procarbazine, prednisone) was used as rescue therapy in 62 dogs refractory to CHOP-based protocols. Overall response rate was 59%, with complete response in 35% of dogs. Median progression-free survival was 78 days. LOPP represents an effective rescue option with manageable toxicity profile.",
        "study_type": "prospective",
        "sample_size": 62,
    },
    {
        "title": "DMAC rescue protocol for relapsed canine multicentric lymphoma",
        "authors": [{"name": "Alvarez FJ"}, {"name": "Kisseberth WC"}],
        "year": 2019,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.00456",
        "abstract": "The DMAC (dexamethasone, melphalan, actinomycin D, cytosine arabinoside) rescue protocol was evaluated in 48 dogs with relapsed lymphoma. Overall response rate was 40%, with a median second remission duration of 54 days. DMAC showed similar efficacy across immunophenotypes but with notable myelosuppression as the primary dose-limiting toxicity.",
        "study_type": "prospective",
        "sample_size": 48,
    },
    {
        "title": "Comparison of rescue protocols for canine lymphoma following CHOP relapse",
        "authors": [{"name": "Zandvliet M"}, {"name": "Rutteman GR"}],
        "year": 2021,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.16234",
        "abstract": "A multicenter retrospective comparing Tanovea, LAP, LOPP, and DMAC rescue protocols in 312 dogs relapsing after CHOP. Tanovea showed the highest complete response rate (28%) followed by LOPP (35% ORR). Duration of first remission strongly predicted rescue protocol efficacy. Sequential rescue protocols provided diminishing returns.",
        "study_type": "retrospective",
        "sample_size": 312,
    },
    # --- Topic 4: T-cell vs B-cell prognosis ---
    {
        "title": "Immunophenotype as a prognostic factor in canine multicentric lymphoma",
        "authors": [{"name": "Aresu L"}, {"name": "Martini V"}],
        "year": 2015,
        "journal": "Veterinary Pathology",
        "doi": "10.1177/0300985815591076",
        "abstract": "Immunophenotype is the strongest independent prognostic factor in canine multicentric lymphoma. In this study of 267 dogs, B-cell lymphoma had a median survival of 365 days versus 159 days for T-cell lymphoma (P<0.001). T-cell phenotype was associated with higher substage b presentation and poorer response to CHOP-based chemotherapy.",
        "study_type": "prospective",
        "sample_size": 267,
    },
    {
        "title": "T-cell lymphoma in dogs: clinical presentation, treatment response, and prognosis",
        "authors": [{"name": "Rebhun RB"}, {"name": "Kent MS"}],
        "year": 2018,
        "journal": "Journal of the American Veterinary Medical Association",
        "doi": "10.2460/javma.252.5.563",
        "abstract": "T-cell immunophenotype in canine lymphoma carries a significantly worse prognosis compared to B-cell disease. Among 180 dogs, T-cell cases had lower complete response rates (52% vs 79% for B-cell), shorter median remission (102 vs 245 days), and shorter overall survival (182 vs 397 days). Gastrointestinal involvement was more common in T-cell cases.",
        "study_type": "retrospective",
        "sample_size": 180,
    },
    {
        "title": "Flow cytometric immunophenotyping and prognosis in canine lymphoma",
        "authors": [{"name": "Avery AC"}, {"name": "Avery PR"}],
        "year": 2020,
        "journal": "Veterinary Clinical Pathology",
        "doi": "10.1111/vcp.00789",
        "abstract": "Flow cytometry-based immunophenotyping of 420 canine lymphoma cases confirmed the prognostic significance of B-cell versus T-cell classification. B-cell lymphoma median survival was 13.2 months compared to 5.8 months for T-cell cases. Within B-cell subtypes, diffuse large B-cell lymphoma had the best prognosis while indolent B-cell lymphomas showed prolonged survival without treatment.",
        "study_type": "retrospective",
        "sample_size": 420,
    },
    {
        "title": "Prognostic factors and survival analysis in 500 dogs with multicentric lymphoma",
        "authors": [{"name": "Valli VE"}, {"name": "San Myint M"}],
        "year": 2013,
        "journal": "Veterinary Pathology",
        "doi": "10.1177/0300985812468524",
        "abstract": "Multivariate analysis of 500 dogs with multicentric lymphoma identified immunophenotype as the most significant prognostic factor. B-cell dogs had 2.1x longer survival than T-cell dogs. Other significant factors included WHO substage, LDH levels, and presence of anemia. T-cell prognosis was particularly poor in dogs with substage b disease.",
        "study_type": "retrospective",
        "sample_size": 500,
    },
    # --- Topic 5: Doxorubicin dose adjustment ---
    {
        "title": "Doxorubicin dose adjustment strategies for chemotherapy-induced neutropenia in dogs",
        "authors": [{"name": "Gustafson DL"}, {"name": "Page RL"}],
        "year": 2016,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.00234",
        "abstract": "Chemotherapy-induced neutropenia is the most common dose-limiting toxicity of doxorubicin in canine lymphoma protocols. This study evaluated 175 dogs receiving CHOP with doxorubicin at 30mg/m2. Grade 3-4 neutropenia occurred in 38% of dogs. A 20% doxorubicin dose reduction was recommended when absolute neutrophil count falls below 1500/uL. Dose-reduced dogs maintained similar remission rates (P=0.34).",
        "study_type": "retrospective",
        "sample_size": 175,
    },
    {
        "title": "Myelosuppression management during CHOP chemotherapy in canine lymphoma",
        "authors": [{"name": "Childress MO"}, {"name": "Ramos-Vara JA"}],
        "year": 2018,
        "journal": "Journal of the American Veterinary Medical Association",
        "doi": "10.2460/javma.253.7.891",
        "abstract": "Guidelines for managing doxorubicin-induced neutropenia during CHOP chemotherapy are presented based on 230 treated dogs. Treatment delays of 5-7 days are recommended for ANC <2000/uL. For recurrent grade 3-4 neutropenia, a 25% dose reduction of doxorubicin is suggested. Prophylactic antibiotics are indicated when ANC falls below 1000/uL. Dose adjustments did not significantly impact overall survival.",
        "study_type": "prospective",
        "sample_size": 230,
    },
    {
        "title": "Pharmacokinetics of doxorubicin in dogs with lymphoma and implications for dose modification",
        "authors": [{"name": "Selting KA"}, {"name": "Lana SE"}],
        "year": 2021,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.16012",
        "abstract": "Population pharmacokinetic modeling of doxorubicin in 95 dogs with lymphoma receiving CHOP. Body weight-based dosing at 1mg/kg provided more consistent drug exposure than BSA-based dosing at 30mg/m2. For neutropenia management, reducing the doxorubicin dose by 20-25% maintains therapeutic drug levels while reducing hematologic toxicity. Individual dose adjustment based on prior cycle nadir neutrophil count improved safety.",
        "study_type": "pharmacokinetic",
        "sample_size": 95,
    },
    # --- Additional cross-topic papers ---
    {
        "title": "Canine lymphoma: a comprehensive review of diagnosis, staging, and treatment",
        "authors": [{"name": "Vail DM"}, {"name": "Thamm DH"}, {"name": "Liptak JM"}],
        "year": 2023,
        "journal": "Withrow and MacEwen's Small Animal Clinical Oncology",
        "doi": "10.1016/B978-0-323-59496-7.00032-0",
        "abstract": "Comprehensive review of canine multicentric lymphoma covering CHOP-based first-line protocols, immunophenotype-based prognosis (B-cell vs T-cell), rescue chemotherapy options including Tanovea, LOPP, and DMAC, and supportive care including doxorubicin dose adjustment for neutropenia. B-cell lymphoma treated with CHOP has the best prognosis with median survival exceeding 12 months.",
        "study_type": "review",
        "sample_size": None,
    },
    {
        "title": "Breed predisposition and clinical characteristics of canine lymphoma subtypes",
        "authors": [{"name": "Pastor M"}, {"name": "Bianchi M"}],
        "year": 2022,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.00812",
        "abstract": "Analysis of breed predisposition in 650 dogs with lymphoma. Golden Retrievers and Boxers were overrepresented. B-cell lymphoma was more common in Golden Retrievers while T-cell lymphoma was overrepresented in Boxers. Breed-specific immunophenotype distributions may influence treatment response and prognosis when selecting between CHOP protocols.",
        "study_type": "retrospective",
        "sample_size": 650,
    },
    {
        "title": "WHO staging and substage classification impact on canine lymphoma outcome",
        "authors": [{"name": "Ponce F"}, {"name": "Marchal T"}],
        "year": 2017,
        "journal": "Veterinary Pathology",
        "doi": "10.1177/0300985817698207",
        "abstract": "WHO clinical staging (I-V) and substage (a vs b) classification were evaluated in 380 dogs with multicentric lymphoma. Stage V and substage b significantly reduced survival independent of immunophenotype. The combination of T-cell immunophenotype and substage b had the worst prognosis with median survival of only 87 days even with CHOP treatment.",
        "study_type": "retrospective",
        "sample_size": 380,
    },
    {
        "title": "Cardiotoxicity monitoring during doxorubicin-based CHOP chemotherapy in dogs",
        "authors": [{"name": "Mauldin GE"}, {"name": "Fox PR"}],
        "year": 2015,
        "journal": "Journal of Veterinary Cardiology",
        "doi": "10.1016/j.jvc.2015.03.001",
        "abstract": "Cardiac monitoring guidelines for dogs receiving doxorubicin within CHOP protocols. Echocardiography before treatment and after cumulative doses exceeding 180mg/m2 is recommended. Cardiotoxicity risk increases with dose. For dogs experiencing both cardiotoxicity and neutropenia, doxorubicin dose reduction of 25% or substitution with mitoxantrone should be considered.",
        "study_type": "prospective",
        "sample_size": 112,
    },
    {
        "title": "Prognostic biomarkers in canine B-cell and T-cell lymphoma",
        "authors": [{"name": "Vernau W"}, {"name": "Moore PF"}],
        "year": 2021,
        "journal": "Veterinary Clinical Pathology",
        "doi": "10.1111/vcp.01023",
        "abstract": "Evaluation of molecular biomarkers in 290 dogs with lymphoma. Ki-67 proliferation index, thymidine kinase activity, and C-reactive protein were significant prognostic markers. B-cell lymphoma with low Ki-67 had the longest survival (median 480 days). T-cell lymphoma with high Ki-67 had the shortest survival (median 120 days). These biomarkers may refine prognosis beyond immunophenotype alone.",
        "study_type": "prospective",
        "sample_size": 290,
    },
]


# ---------------------------------------------------------------------------
# Canine carcinoma corpus -- mediastinal tumors, hypercalcemia, treatment,
# prognosis, differential diagnosis
# ---------------------------------------------------------------------------
CANINE_CARCINOMA_PAPERS: list[dict] = [
    # === TOPIC 6: Canine Mediastinal/Thoracic Tumors ===
    {
        "title": "Clinical features, treatment options, and outcome in dogs with thymoma: 116 cases (1999-2010)",
        "authors": [{"name": "Robat CS"}, {"name": "Cesario L"}, {"name": "Gaeta R"}, {"name": "Miller M"}, {"name": "Schrempp D"}, {"name": "Chun R"}],
        "year": 2013,
        "journal": "Journal of the American Veterinary Medical Association",
        "doi": "10.2460/javma.243.10.1448",
        "abstract": "Objective: To characterize clinical features, diagnostic findings, treatment options, and outcome in dogs with thymoma. Design: Multi-institutional retrospective case series. Animals: 116 client-owned dogs with thymoma. Results: 38% were Labrador or Golden Retrievers. 17% had signs of myasthenia gravis and 34% had hypercalcemia at diagnosis. Surgical excision was performed in 72% of cases, yielding a median survival of 635 days compared to 76 days without surgery. Shorter survival was associated with concurrent tumors at diagnosis, lack of surgical intervention, and higher pathological staging. Dogs with thymoma had a good prognosis following surgery.",
        "study_type": "retrospective",
        "sample_size": 116,
    },
    {
        "title": "Canine Epithelial Thymic Tumors: Outcome in 28 Dogs Treated by Surgery",
        "authors": [{"name": "Martano M"}, {"name": "Buracco P"}, {"name": "Morello EM"}],
        "year": 2021,
        "journal": "Animals",
        "doi": "10.3390/ani11123444",
        "abstract": "Thymoma is a tumor rarely reported in dogs and should be differentiated from mediastinal lymphoma. Twenty-eight dogs were evaluated: 18 with thymomas and 10 with thymic carcinomas, classified according to WHO classification (Types A, AB, B1, B2, B3, and C). Median overall survival was 1173 days and disease-free interval was 903 days. Dogs with thymic carcinoma experienced significantly shorter disease-free intervals. Masaoka Stage III tumors demonstrated worse clinical outcomes. Surgical excision remains the primary treatment approach, with adjuvant therapies potentially extending survival in specific cases.",
        "study_type": "retrospective",
        "sample_size": 28,
    },
    {
        "title": "Cranial mediastinal carcinomas in nine dogs",
        "authors": [{"name": "Liptak JM"}, {"name": "Kamstock DA"}, {"name": "Dernell WS"}, {"name": "Ehrhart EJ"}, {"name": "Rizzo SA"}, {"name": "Withrow SJ"}],
        "year": 2008,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/j.1476-5829.2007.00133.x",
        "abstract": "Nine dogs with cranial mediastinal carcinomas were evaluated. Histological examination revealed four ectopic follicular cell thyroid carcinomas, one ectopic medullary cell thyroid carcinoma, two neuroendocrine carcinomas, and two anaplastic carcinomas. One dog presented with functional hyperthyroidism. Surgical resection was attempted in eight dogs with complete resection achieved in six. Post-operative complications included pulmonary thromboembolism in four dogs. The median survival time was 243 days. Local invasion and pleural effusion had minimal negative impact on outcomes.",
        "study_type": "case_series",
        "sample_size": 9,
    },
    {
        "title": "A retrospective study of prognostic factors in 29 dogs with surgically treated thymic epithelial tumors",
        "authors": [{"name": "Hashimoto Y"}, {"name": "Nagakubo D"}, {"name": "Muta K"}, {"name": "Tsuboi M"}, {"name": "Nakagawa T"}, {"name": "Nishimura R"}],
        "year": 2025,
        "journal": "Canadian Journal of Veterinary Research",
        "doi": "",
        "abstract": "This investigation examined whether paraneoplastic syndromes, Masaoka classification, and WHO classification correlate with survival outcomes in canine thymic epithelial tumors. Among 29 surgically treated dogs, hypercalcemia and anemia emerged as observable paraneoplastic manifestations. Hypercalcemia did not result in a statistical difference in median survival duration. WHO histological classification may provide prognostic value comparable to Masaoka staging for predicting patient outcomes.",
        "study_type": "retrospective",
        "sample_size": 29,
    },
    {
        "title": "Preoperative management and postoperative complications in 9 dogs undergoing surgical treatment of thymic-associated myasthenia gravis",
        "authors": [{"name": "Saylor SE"}, {"name": "Oblak ML"}, {"name": "Risselada M"}, {"name": "Thieman KM"}, {"name": "McKenna C"}, {"name": "Scharf VF"}],
        "year": 2024,
        "journal": "Canadian Veterinary Journal",
        "doi": "",
        "abstract": "Nine dogs with thymic epithelial tumors and paraneoplastic myasthenia gravis were studied. Six dogs received preoperative medical management lasting a median of 7.5 days. Three dogs experienced immediate postoperative complications resulting in euthanasia. Of the six survivors, three demonstrated complete clinical resolution of myasthenia gravis signs while two showed partial improvement. Dogs with thymic epithelial tumors and paraneoplastic myasthenia gravis are at high risk for perioperative complications.",
        "study_type": "retrospective",
        "sample_size": 9,
    },
    {
        "title": "Mediastinal lymphoma in dogs is homogeneous compared to thymic epithelial neoplasia and is more likely to envelop the cranial vena cava in CT images",
        "authors": [{"name": "Reeve EJ"}, {"name": "Mapletoft EK"}, {"name": "Schiborra F"}, {"name": "Maddox TW"}, {"name": "Lamb CR"}, {"name": "Warren-Smith CMR"}],
        "year": 2020,
        "journal": "Veterinary Radiology and Ultrasound",
        "doi": "10.1111/vru.12812",
        "abstract": "CT imaging characteristics of canine cranial mediastinal lymphoma (n=33) versus thymic epithelial neoplasia (n=29) were compared. Thymic epithelial neoplasia was associated with heterogeneous attenuation while lymphoma demonstrated homogeneous appearance. Lymphoma cases exhibited significantly greater likelihood of enveloping the cranial vena cava. Dogs with thymic tumors were older (median 8.6 vs 6.0 years). Standard deviation of Hounsfield units in post-contrast images exceeded 17HU for thymic neoplasms with 72% sensitivity and 79% specificity.",
        "study_type": "retrospective",
        "sample_size": 62,
    },
    # === TOPIC 7: Carcinoma with Paraneoplastic Hypercalcemia ===
    {
        "title": "Identification of parathyroid hormone-related protein in canine apocrine adenocarcinoma of the anal sac",
        "authors": [{"name": "Rosol TJ"}, {"name": "Capen CC"}, {"name": "Danks JA"}, {"name": "Suva LJ"}, {"name": "Steinmeyer CL"}, {"name": "Hayman J"}, {"name": "Ebeling PR"}, {"name": "Martin TJ"}],
        "year": 1990,
        "journal": "Veterinary Pathology",
        "doi": "10.1177/030098589002700203",
        "abstract": "The presence of parathyroid hormone-related protein (PTHrP) was demonstrated in tumor cells derived from a hypercalcemic dog using Western and Northern blot analyses. A major protein with a molecular weight of approximately 18,000 daltons reacted with antisera to human PTHrP. Immunohistochemical staining revealed PTHrP in tumor samples, with positive results in 13 of 24 tumors maintained in mice and in 3 of 10 adenocarcinomas from hypercalcemic dogs. Canine tissues contained a PTHrP homologue likely relevant to malignancy-related hypercalcemia pathogenesis.",
        "study_type": "prospective",
        "sample_size": 34,
    },
    {
        "title": "Parathyroid hormone (PTH)-related protein, PTH, and 1,25-dihydroxyvitamin D in dogs with cancer-associated hypercalcemia",
        "authors": [{"name": "Rosol TJ"}, {"name": "Nagode LA"}, {"name": "Couto CG"}, {"name": "Hammer AS"}, {"name": "Chew DJ"}, {"name": "Peterson JL"}, {"name": "Ayl RD"}, {"name": "Steinmeyer CL"}, {"name": "Capen CC"}],
        "year": 1992,
        "journal": "Endocrinology",
        "doi": "10.1210/endo.131.3.1505457",
        "abstract": "PTHrP, PTH, and 1,25-dihydroxyvitamin D were measured in dogs with cancer-associated hypercalcemia. PTHrP levels were undetectable (less than 1.8 pM) in normal dogs but elevated in cancer-affected dogs, particularly those with anal sac adenocarcinomas (44.9 +/- 27 pM) and lymphoma. PTH concentrations remained normal except in dogs with parathyroid adenomas. Circulating concentrations of PTHrP are consistently increased in dogs with cancer-associated hypercalcemia, and PTHrP appears to play an important role in the induction of hypercalcemia.",
        "study_type": "prospective",
        "sample_size": 50,
    },
    {
        "title": "Paraneoplastic hypercalcemia in a dog with thyroid carcinoma",
        "authors": [{"name": "Lane AE"}, {"name": "Wyatt KM"}],
        "year": 2012,
        "journal": "Canadian Veterinary Journal",
        "doi": "",
        "abstract": "A male Beagle presented with thyroid carcinoma and elevated calcium levels. Following surgical removal of the thyroid tumor, the dog developed persistently low calcium requiring ongoing supplementation with calcitriol and calcium carbonate over two years. The dog died from renal failure with no evidence of thyroid carcinoma. This report documents the unusual progression from paraneoplastic hypercalcemia to chronic hypocalcemia post-thyroidectomy.",
        "study_type": "case_series",
        "sample_size": 1,
    },
    {
        "title": "Hypercalcemia of Malignancy in a Dog Diagnosed With Cholangiocellular Carcinoma",
        "authors": [{"name": "Martinez-Sogues L"}, {"name": "Vila A"}, {"name": "Roura X"}, {"name": "Pastor J"}, {"name": "Novellas R"}, {"name": "Marco A"}, {"name": "Cuvertoret-Sanz M"}, {"name": "Martinez J"}, {"name": "Solano-Gallego L"}],
        "year": 2019,
        "journal": "Topics in Companion Animal Medicine",
        "doi": "10.1053/j.tcam.2019.02.001",
        "abstract": "A four-year-old neutered male Golden Retriever presented with weight loss, polyuria, and polydipsia. Diagnostic findings included elevated ionized calcium, elevated kidney markers, and severe hyperlipasemia. Abdominal ultrasound revealed multiple hepatic nodules with cytological diagnosis indicating malignant epithelial neoplasia consistent with bile duct adenocarcinoma. Serum PTHrP concentration was increased. Treatment included fluids, furosemide, and prednisone. This represents the first report of malignant hypercalcemia associated with cholangiocellular carcinoma in a dog.",
        "study_type": "case_series",
        "sample_size": 1,
    },
    {
        "title": "Animal Models of Cancer-Associated Hypercalcemia",
        "authors": [{"name": "Kohart NA"}, {"name": "Elshafae SM"}, {"name": "Breitbach JT"}, {"name": "Rosol TJ"}],
        "year": 2017,
        "journal": "Veterinary Sciences",
        "doi": "10.3390/vetsci4020021",
        "abstract": "Humoral hypercalcemia of malignancy (HHM) is the most common mechanism of cancer-associated hypercalcemia and is due to tumor-derived factors including parathyroid hormone-related protein (PTHrP). The second mechanism involves localized bone destruction near tumors. This review compares disease presentation across humans and animals, examining spontaneous and experimentally-induced animal models used to study the mechanisms of cancer-associated hypercalcemia, spanning rodents, dogs, cats, and horses.",
        "study_type": "review",
        "sample_size": None,
    },
    {
        "title": "Canine Apocrine Gland Anal Sac Adenocarcinoma: A Review",
        "authors": [{"name": "Repasy AB"}, {"name": "Selmic LE"}, {"name": "Kisseberth WC"}],
        "year": 2022,
        "journal": "Topics in Companion Animal Medicine",
        "doi": "10.1016/j.tcam.2022.100682",
        "abstract": "Apocrine gland anal sac adenocarcinoma (AGASAC), while relatively uncommon, is one of the most common causes of paraneoplastic hypercalcemia in dogs. Approximately 25% of dogs with AGASAC present with hypercalcemia. Clinical presentations typically involve obstruction from the tumor or metastatic lymph nodes along with effects from hypercalcemia. The preferred treatment combines surgical removal with radiation and chemotherapy. Prolonged survival times are possible, particularly for dogs with smaller tumors receiving additional treatments for recurrence. Overall median survival is approximately 18 months.",
        "study_type": "review",
        "sample_size": None,
    },
    # === TOPIC 8: Treatment Protocols ===
    {
        "title": "Hypofractionated radiation therapy in the treatment of canine thymoma: Retrospective study of eight cases",
        "authors": [{"name": "Goto S"}, {"name": "Murakami M"}, {"name": "Kawabe M"}, {"name": "Iwasaki R"}, {"name": "Heishima K"}, {"name": "Sakai H"}, {"name": "Mori T"}],
        "year": 2017,
        "journal": "Veterinary Radiology and Ultrasound",
        "doi": "10.1111/vru.12525",
        "abstract": "This retrospective observational study examined outcomes from a hypofractionated radiation protocol for confirmed thymoma cases in eight dogs. Treatment involved 48-49 Gy delivered over six to seven weekly fractions. Two dogs achieved complete responses, two achieved partial responses, and the disease remained stable in two, with a 50% overall response rate. Median survival time was not reached, with a 75% one-year survival rate. Side effects were common in the skin and/or lung and were self-limiting or asymptomatic. Hypofractionated radiation therapy was well tolerated and may serve as an option when surgery is declined or tumors are unresectable.",
        "study_type": "retrospective",
        "sample_size": 8,
    },
    {
        "title": "Toceranib phosphate in the treatment of canine thyroid carcinoma: 42 cases (2009-2018)",
        "authors": [{"name": "Sheppard-Olivares S"}, {"name": "Bello NM"}, {"name": "Wood E"}, {"name": "Szivek A"}, {"name": "Biller B"}, {"name": "Hocker S"}, {"name": "Wouda RM"}],
        "year": 2020,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.12571",
        "abstract": "This retrospective analysis examined toceranib effectiveness in treating canine thyroid carcinoma across 42 dogs divided into treatment-naive (n=26) and prior therapy (n=16) groups. 88.4% and 75% of dogs experienced clinical benefit in the naive and prior therapy settings, respectively. Median progression-free intervals were 206 days (naive) and 1015 days (prior therapy). Median overall survival times were 563 days and 1082 days respectively. The research demonstrates minimal adverse effects and comparable outcomes between treatment settings.",
        "study_type": "retrospective",
        "sample_size": 42,
    },
    {
        "title": "Retrospective Evaluation of a Combination of Carboplatin and Bleomycin for the Treatment of Canine Carcinomas",
        "authors": [{"name": "Giuliano A"}, {"name": "Almendros A"}],
        "year": 2022,
        "journal": "Animals",
        "doi": "10.3390/ani12182340",
        "abstract": "Safety and efficacy of combined carboplatin-bleomycin chemotherapy was evaluated in 30 dogs with various carcinomas. Treatment was well tolerated with 53% developing mild side effects. Gastrointestinal issues appeared in 46% and hematological abnormalities in 30%. 76% of cases achieved clinical benefit (partial response plus stable disease) with 24% showing objective partial responses. The combination appears safe and potentially effective for some types of carcinomas, though larger prospective studies are needed.",
        "study_type": "retrospective",
        "sample_size": 30,
    },
    {
        "title": "Safety evaluation of combination carboplatin and toceranib phosphate (Palladia) in tumour-bearing dogs: A phase I dose finding study",
        "authors": [{"name": "Wouda RM"}, {"name": "Hocker SE"}, {"name": "Higginbotham ML"}],
        "year": 2018,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.12332",
        "abstract": "Prospective phase I dose-finding clinical trial combining carboplatin with toceranib phosphate in tumor-bearing dogs. Eleven dogs with various malignancies received toceranib at 2.75 mg/kg orally every other day plus carboplatin IV every 21 days at escalating doses starting at 200 mg/m2. MTDs were identified as carboplatin 200 mg/m2 IV every 21 days and toceranib 2.75 mg/kg PO EOD. Neutropenia was the dose-limiting toxicity. Two subjects showed partial response while six maintained stable disease. Combination was well tolerated.",
        "study_type": "prospective",
        "sample_size": 11,
    },
    {
        "title": "Evaluation of adjuvant carboplatin chemotherapy in the management of surgically excised anal sac apocrine gland adenocarcinoma in dogs",
        "authors": [{"name": "Wouda RM"}, {"name": "Borrego J"}, {"name": "Keuler NS"}, {"name": "Stein T"}],
        "year": 2016,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.12068",
        "abstract": "Carboplatin's role in post-operative care for canine anal sac apocrine gland adenocarcinoma was evaluated. Seventy-four dogs underwent surgery with 44 receiving adjuvant carboplatin and 30 receiving surgery alone. Median overall survival was 703 days and median time to progression was 384 days. Only primary tumor size and lymph node metastasis at diagnosis significantly impacted outcome. Carboplatin did not significantly improve OS or TTP but was associated with reduced local recurrence rates.",
        "study_type": "retrospective",
        "sample_size": 74,
    },
    {
        "title": "A prospective, multi-centre, Veterinary Radiation Therapy Oncology Group study reveals potential efficacy of toceranib phosphate (Palladia) as a primary or adjuvant agent in the treatment of canine nasal carcinoma",
        "authors": [{"name": "Ehling TJ"}, {"name": "Klein MK"}, {"name": "Smith L"}, {"name": "Prescott D"}, {"name": "Haney S"}, {"name": "Looper J"}, {"name": "LaDue T"}, {"name": "Brawner W"}, {"name": "Fidel J"}, {"name": "Shiomitsu K"}, {"name": "Green E"}, {"name": "Saba C"}, {"name": "Turek M"}, {"name": "Farrelly J"}],
        "year": 2022,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.12776",
        "abstract": "Sixty-three dogs with nasal carcinoma were enrolled across ten sites to evaluate toceranib phosphate alone or combined with radiation therapy. Overall response rates were significantly improved in the toceranib plus RT arm (79.4%) and RT alone (68.9%) over toceranib alone (22%). Clinical benefit rates reached 97.3% in the combined treatment arm. Median survival times were 615 days (toceranib+RT), 368 days (RT alone), and 298 days (toceranib alone). Toceranib did not potentiate radiation side effects.",
        "study_type": "prospective",
        "sample_size": 63,
    },
    {
        "title": "Retrospective evaluation of toceranib phosphate (Palladia) in the treatment of canine carcinomatosis and mesothelioma",
        "authors": [{"name": "Hicks KA"}, {"name": "Leeper HJ"}, {"name": "Curran KM"}],
        "year": 2024,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.12972",
        "abstract": "Toceranib phosphate effectiveness was evaluated in treating canine carcinomatosis and mesothelioma in 23 dogs. 82% presented with effusion. Best overall response rate was 30.4% comprising 13% complete responses and 17.3% partial responses. Stable disease occurred in 60.8% of cases. Grade 1 and 2 diarrhea or hyporexia were primary adverse effects. Median progression-free survival was 171 days and overall median survival was 301 days.",
        "study_type": "retrospective",
        "sample_size": 23,
    },
    {
        "title": "Phase II evaluation of doxorubicin for treatment of various canine neoplasms",
        "authors": [{"name": "Ogilvie GK"}, {"name": "Reynolds HA"}, {"name": "Richardson RC"}, {"name": "Withrow SJ"}, {"name": "Norris AM"}, {"name": "Henderson RA"}, {"name": "Klausner JS"}, {"name": "Fowler JD"}, {"name": "McCaw D"}],
        "year": 1989,
        "journal": "Journal of the American Veterinary Medical Association",
        "doi": "",
        "abstract": "185 dogs with confirmed malignant tumors were evaluated for responses to two doses of doxorubicin (30 mg/m2 IV, 21 days apart). Among 157 evaluable dogs, a partial or complete remission was obtained in 41% overall. Response rates by tumor type: lymphoma 67% (42/63), carcinoma 26% (11/43), sarcoma 22%. Various tumor types demonstrated partial to complete remissions. This study established doxorubicin as a broad-spectrum chemotherapy agent in veterinary oncology.",
        "study_type": "prospective",
        "sample_size": 185,
    },
    {
        "title": "Toceranib phosphate (Palladia) for the treatment of canine exocrine pancreatic adenocarcinoma",
        "authors": [{"name": "Musser ML"}, {"name": "Johannes CM"}],
        "year": 2021,
        "journal": "BMC Veterinary Research",
        "doi": "10.1186/s12917-021-02978-8",
        "abstract": "Eight dogs with confirmed pancreatic cancer were retrospectively analyzed for toceranib effectiveness. The medication was well tolerated across all patients. Among six treated with gross disease, four underwent imaging evaluation showing one partial response, two with stable disease, and one with progressive disease yielding a 75% clinical benefit rate. Median overall survival reached 89.5 days (range 14-506 days). Findings suggest toceranib demonstrates biological activity in canine pancreatic carcinoma.",
        "study_type": "retrospective",
        "sample_size": 8,
    },
    {
        "title": "Canine intranasal tumours treated with alternating carboplatin and doxorubicin in conjunction with oral piroxicam: 29 cases",
        "authors": [{"name": "Woodruff MJ"}, {"name": "Heading KL"}, {"name": "Bennett P"}],
        "year": 2019,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.12443",
        "abstract": "Twenty-nine dogs with histologically confirmed nasal tumors received alternating carboplatin and doxorubicin with oral piroxicam between 2004-2017. Overall median survival was 234 days, with adenocarcinoma/carcinoma achieving 280 days and sarcomas 448 days. Adverse events occurred in approximately 69% but the chemotherapy protocol was generally well tolerated. Potential therapeutic benefit demonstrated for specific tumor types when chemotherapy is used as monotherapy.",
        "study_type": "retrospective",
        "sample_size": 29,
    },
    # === TOPIC 9: Prognosis and Staging ===
    {
        "title": "Thyroidectomy in dogs with thyroid tumors: Survival analysis in 144 cases (1994-2018)",
        "authors": [{"name": "Enache D"}, {"name": "Ferro L"}, {"name": "Morello EM"}, {"name": "Massari F"}, {"name": "Romanelli G"}, {"name": "Nicoli S"}, {"name": "Guazzetti S"}, {"name": "Porporato F"}, {"name": "Zini E"}],
        "year": 2023,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1111/jvim.16644",
        "abstract": "Survival outcomes were analyzed in 144 dogs undergoing thyroidectomy for thyroid neoplasia. 77.4% survived beyond 500 days. Nonfollicular carcinomas, metastases at diagnosis, and adjuvant chemotherapy administration were associated with significantly elevated thyroid cancer mortality risk. Thrombosis occurred in 40 dogs and was associated with increased risk of death from other causes. Thyroidectomy remained a viable treatment consideration even in selected cases with metastatic disease.",
        "study_type": "retrospective",
        "sample_size": 144,
    },
    {
        "title": "Canine thyroid carcinoma",
        "authors": [{"name": "Liptak JM"}],
        "year": 2007,
        "journal": "Clinical Techniques in Small Animal Practice",
        "doi": "10.1053/j.ctsap.2007.03.007",
        "abstract": "Review of canine thyroid carcinoma examining malignant thyroid tumors which are relatively prevalent in dogs. Most tumors are unilateral and nonfunctional. Assessment should determine whether tumors are mobile or fixed/invasive. Surgical removal is advised for unilateral mobile carcinomas while radiation or radioactive iodine suits invasive or bilateral cases. Adjunctive chemotherapy is considered for high-risk tumors. The prognosis is good following surgical treatment of mobile thyroid tumors and irradiation of fixed thyroid carcinomas, with median survival times greater than 3 years.",
        "study_type": "review",
        "sample_size": None,
    },
    {
        "title": "Canine thyroid carcinomas: A review with emphasis on comparing the compact subtype of follicular thyroid carcinomas and medullary thyroid carcinomas",
        "authors": [{"name": "Athey JM"}, {"name": "Vieson MD"}, {"name": "Bailey K"}, {"name": "Rudmann D"}, {"name": "Baumgartner WA"}, {"name": "Selting KA"}],
        "year": 2024,
        "journal": "Veterinary Pathology",
        "doi": "10.1177/03009858231177225",
        "abstract": "This review focuses on differentiating compact follicular thyroid carcinoma from medullary thyroid carcinoma in dogs. Both subtypes share similar histomorphologic features which can lead to misclassification. Accurate distinction is important for prognostication and treatment planning. The review discusses histopathological features, immunohistochemistry panels, and clinical behavior differences between these subtypes.",
        "study_type": "review",
        "sample_size": None,
    },
    # === TOPIC 10: Differential Diagnosis ===
    {
        "title": "Diagnosis of mediastinal masses in dogs by flow cytometry",
        "authors": [{"name": "Lana S"}, {"name": "Plaza S"}, {"name": "Hampe K"}, {"name": "Burnett R"}, {"name": "Avery AC"}],
        "year": 2006,
        "journal": "Journal of Veterinary Internal Medicine",
        "doi": "10.1892/0891-6640(2006)20[1161:dommid]2.0.co;2",
        "abstract": "Flow cytometry was investigated for differentiating thymoma from lymphoma in canine mediastinal masses. All six thymoma cases contained 10% or more lymphocytes coexpressing CD4 and CD8, characteristic of thymocytes. Six of seven lymphomas contained less than 2% CD4+CD8+ lymphocytes. Flow cytometry successfully identified lymphocyte-rich mediastinal masses in all 13 cases studied, potentially reducing the need for invasive surgical biopsies. CD4+CD8+ double-positive lymphocytes greater than 10% is highly specific for thymoma.",
        "study_type": "prospective",
        "sample_size": 13,
    },
    {
        "title": "Radiographic Differentiation of Cranial Mediastinal Lymphomas from Thymic Epithelial Tumors in Dogs and Cats",
        "authors": [{"name": "Oura TJ"}, {"name": "Hamel PE"}, {"name": "Jennings SH"}, {"name": "Bain PE"}, {"name": "Jennings DE"}, {"name": "Berg J"}],
        "year": 2019,
        "journal": "Journal of the American Animal Hospital Association",
        "doi": "10.5326/JAAHA-MS-6907",
        "abstract": "Thoracic radiographic findings were examined to differentiate between lymphomas and thymic epithelial tumors in 62 dogs and 28 cats across 17 radiographic criteria. In dogs, cranial mediastinal masses with at least two well-defined radiographic margins on a lateral view and those causing rightward cardiac shift were significantly more suggestive of epithelial tumors rather than lymphomas. Radiographic evaluation may provide preliminary diagnostic guidance but does not eliminate the need for tissue sampling.",
        "study_type": "retrospective",
        "sample_size": 90,
    },
    {
        "title": "Patient Characteristics, Prognostic Factors and Outcome of Dogs with High-Grade Primary Mediastinal Lymphoma",
        "authors": [{"name": "Moore EL"}, {"name": "Vernau W"}, {"name": "Rebhun RB"}, {"name": "Skorupski KA"}, {"name": "Burton JH"}],
        "year": 2018,
        "journal": "Veterinary and Comparative Oncology",
        "doi": "10.1111/vco.12331",
        "abstract": "Forty-two dogs with high-grade primary mediastinal lymphoma were retrospectively evaluated. Common presenting signs included lethargy, anorexia, and polyuria/polydipsia. Hypercalcemia and pleural effusion were frequently observed at diagnosis. Nearly all cases exhibited T-cell phenotype typically paired with lymphoblastic morphology per WHO classification. Median progression-free and overall survival reached 133 and 183 days respectively. CHOP chemotherapy demonstrated improved outcomes. Absence of pleural effusion associated with better overall survival.",
        "study_type": "retrospective",
        "sample_size": 42,
    },
    {
        "title": "Cytokeratin and vimentin co-expression in 21 canine primary pulmonary epithelial neoplasms",
        "authors": [{"name": "Burgess HJ"}, {"name": "Kerr ME"}],
        "year": 2009,
        "journal": "Journal of Veterinary Diagnostic Investigation",
        "doi": "10.1177/104063870902100607",
        "abstract": "Twenty-one canine primary pulmonary epithelial neoplasms were evaluated for cytokeratin and vimentin expression. All neoplasms stained positive for cytokeratin while only 8 (38%) stained positive for both cytokeratin and vimentin. Adenocarcinomas were the predominant histologic type. Papillary adenocarcinomas were consistently vimentin negative while anaplastic patterns demonstrated elevated vimentin staining. The frequency of co-expression matched patterns observed in human pulmonary tumors.",
        "study_type": "prospective",
        "sample_size": 21,
    },
    {
        "title": "Rapid immunocytochemistry for the detection of cytokeratin and vimentin: assessment of its diagnostic value in neoplastic diseases of dogs",
        "authors": [{"name": "Sawa M"}, {"name": "Inoue M"}, {"name": "Yabuki A"}, {"name": "Kohyama M"}, {"name": "Miyoshi N"}, {"name": "Setoguchi A"}, {"name": "Yamato O"}],
        "year": 2017,
        "journal": "Veterinary Clinical Pathology",
        "doi": "10.1111/vcp.12462",
        "abstract": "A rapid immunocytochemistry method for detecting cytokeratin and vimentin markers was evaluated in 30 canine tumor samples. The rapid method detected specific signals in 83.3% of cases with almost perfect agreement (kappa=0.857) for both markers in nonepithelial tumors and fair agreement in epithelial tumors compared to standard IHC. This approach serves as a practical diagnostic tool for distinguishing epithelial from non-epithelial tumor cell origins in veterinary cytology.",
        "study_type": "prospective",
        "sample_size": 30,
    },
]

# Combined list for seeding
SEED_PAPERS: list[dict] = SEED_PAPERS + CANINE_CARCINOMA_PAPERS
