import type { BodySystem } from "./types";

export const BODY_SYSTEMS: BodySystem[] = [
  {
    id: "nervous",
    name_it: "Sistema nervoso",
    name_en: "Nervous system",
    emoji: "\u{1F9E0}",
    structures: ["Cervello", "Midollo spinale", "Nervi"],
    description: "Controlla tutte le funzioni del corpo e le risposte agli stimoli",
    position: { top: "12%", left: "78%" },
    color: "#8b5cf6",
  },
  {
    id: "circulatory",
    name_it: "Apparato circolatorio",
    name_en: "Circulatory system",
    emoji: "\u{2764}\u{FE0F}",
    structures: ["Cuore", "Sangue", "Vasi sanguigni"],
    description: "Trasporta ossigeno, nutrienti e ormoni",
    position: { top: "38%", left: "58%" },
    color: "#ef4444",
  },
  {
    id: "respiratory",
    name_it: "Apparato respiratorio",
    name_en: "Respiratory system",
    emoji: "\u{1FAC1}",
    structures: ["Naso", "Trachea", "Bronchi", "Polmoni"],
    description: "Permette lo scambio di ossigeno e anidride carbonica",
    position: { top: "32%", left: "65%" },
    color: "#06b6d4",
  },
  {
    id: "digestive",
    name_it: "Apparato digerente",
    name_en: "Digestive system",
    emoji: "\u{1F356}",
    structures: ["Bocca", "Esofago", "Stomaco", "Intestino tenue e crasso", "Fegato", "Pancreas"],
    description: "Trasforma il cibo in energia e nutrienti",
    position: { top: "52%", left: "50%" },
    color: "#f59e0b",
  },
  {
    id: "muscular",
    name_it: "Apparato muscolare",
    name_en: "Muscular system",
    emoji: "\u{1F4AA}",
    structures: ["Muscoli scheletrici", "Muscoli lisci", "Muscoli cardiaci"],
    description: "Permette movimento, postura e attivit\u00e0 interne",
    position: { top: "45%", left: "30%" },
    color: "#d946ef",
  },
  {
    id: "skeletal",
    name_it: "Apparato scheletrico",
    name_en: "Skeletal system",
    emoji: "\u{1F9B4}",
    structures: ["Ossa", "Articolazioni", "Cartilagini"],
    description: "Sostiene il corpo e protegge gli organi",
    position: { top: "62%", left: "25%" },
    color: "#a3a3a3",
  },
  {
    id: "integumentary",
    name_it: "Apparato tegumentario",
    name_en: "Integumentary system",
    emoji: "\u{1F9F4}",
    structures: ["Pelle", "Pelo", "Unghie"],
    description: "Protegge il corpo e regola la temperatura",
    position: { top: "25%", left: "38%" },
    color: "#fb923c",
  },
  {
    id: "endocrine",
    name_it: "Sistema endocrino",
    name_en: "Endocrine system",
    emoji: "\u{1F9EC}",
    structures: ["Ghiandole endocrine (tiroide, surrenali, ecc.)"],
    description: "Produce ormoni che regolano molte funzioni corporee",
    position: { top: "22%", left: "68%" },
    color: "#14b8a6",
  },
  {
    id: "immune",
    name_it: "Sistema immunitario (linfatico)",
    name_en: "Immune/Lymphatic system",
    emoji: "\u{1F6E1}\u{FE0F}",
    structures: ["Linfonodi", "Milza", "Vasi linfatici"],
    description: "Difende l\u2019organismo da infezioni e malattie",
    position: { top: "42%", left: "72%" },
    color: "#22c55e",
  },
  {
    id: "urinary",
    name_it: "Apparato urinario",
    name_en: "Urinary system",
    emoji: "\u{1F6BD}",
    structures: ["Reni", "Ureteri", "Vescica", "Uretra"],
    description: "Elimina le sostanze di scarto e regola i liquidi",
    position: { top: "58%", left: "42%" },
    color: "#3b82f6",
  },
  {
    id: "reproductive",
    name_it: "Apparato riproduttore",
    name_en: "Reproductive system",
    emoji: "\u{1F43E}",
    structures: ["Organi sessuali"],
    description: "Permette la riproduzione",
    position: { top: "68%", left: "38%" },
    color: "#ec4899",
  },
  {
    id: "sensory",
    name_it: "Organi di senso",
    name_en: "Sensory organs",
    emoji: "\u{1F443}",
    structures: ["Occhi (vista)", "Orecchie (udito)", "Naso (olfatto)", "Lingua (gusto)"],
    description: "Permettono al cane di percepire l\u2019ambiente",
    position: { top: "15%", left: "85%" },
    color: "#6366f1",
  },
];

export const EVIDENCE_CONFIG: Record<string, { label: string; color: string; bg: string; border: string }> = {
  ALTO: { label: "Evidenza alta", color: "text-emerald-800", bg: "bg-emerald-50", border: "border-emerald-200" },
  MODERATO: { label: "Evidenza moderata", color: "text-amber-800", bg: "bg-amber-50", border: "border-amber-200" },
  BASSO: { label: "Evidenza bassa", color: "text-red-800", bg: "bg-red-50", border: "border-red-200" },
};
